on:
  push:
    paths:
      - 'encodely-common/**'
      - 'encodely-core/**'
      - 'encodely-docker-api/**'
      - 'encodely-job-manager/**'
  pull_request:
    paths:
      - 'encodely-common/**'
      - 'encodely-core/**'
      - 'encodely-docker-api/**'
      - 'encodely-job-manager/**'

name: Continuous-integration-core

jobs:
  check:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Using Java 15
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.sonar/cache
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Analyze
        run: ./gradlew build sonarqube --info
