spring:
  application:
    name: Encodely
  datasource:
    url: jdbc:h2:file:./.data/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

application:
  transcode-container: "jrottenberg/ffmpeg"
  cache-duration-in-seconds: 3600
